### ISSUE TITLE
6. Grouping Elements - Stray [action], Possible Common Student Question?

### ISSUE THREAD

**Issue by pomfy113** [MakeSchool-Tutorials/sa-2018-landing-page#13]
> Instead, it's main purpose is to provide an easy way to target and each group.
> ... and it's content.
"It's" into "its"

One of the solutions just has '[action]' on it without anything around.

> (by default.) 

I'm not sure if I'm getting too nitpicky with these periods before parenthesis

Should we talk to the students about why sometimes, some elements like margin/padding have 2, 3, or 4 things?

**Comment by dionlarson** [comment]
No, I agree they should be on the outside. I've gone through and actually moved them on all tutorials for this summer to keep it consistent.
