### ISSUE TITLE
9. Grid System - Minor Bits and Strays

### ISSUE THREAD

**Issue by pomfy113** [MakeSchool-Tutorials/sa-2018-landing-page#17]
Multiple 'it's' need to change to 'its'. The markdowns with the strange colors are a minor issue, but I still feel as if they need to be fixed. Uneven spacing for the html elements here and there, such as:

```     
<li>Cats are asleep for 70% of their life</li>
   <li>Cats are better at problem-solving than dogs</li>
<li>Cats sweat through their paws</li>
   <li>Abraham Lincoln kept four cats in the White House</li>
```

Alternating them here since what's they look like in code. It's easy to read, though it's unconventional. Not sure what the call is.

Stray ``` sitting around.

More parenthesis periods.

**Comment by dionlarson** [comment]
The syntax highlight fixes actually fix this the indentation as well (it's fine in the source markdown).
