### ISSUE TITLE
3. HTML Basics - Stray characters, minor spelling, markdown issues

### ISSUE THREAD

**Issue by pomfy113** [MakeSchool-Tutorials/sa-2018-landing-page#9]
> ... how your web page looks (how the code is displayed.)
>(We'll learn about styling our HTML elements in the next section.)

Periods are typically outside parenthesis.

> along-side

Spelled "alongside".

> Two additional notes to help you along: - Don't forget to delete our previous "Hello, World!" code - The anchor element should point to the URL https://www.sfspca.org/adoptions/cats

Was this meant to be bullets?

>The image 
>
>element allows you to add images in your web page. The image element is a void element, meaning it doesn't have a closing tag. We can add a image to our HTML doc like so:

Errant newline.

> A unordered list is a collection (aka list) of elements that is usually displayed as a bulleted list. To create a unordered list...

"An" unordered.

```
<ul>
>
</ul>
```

Extra >?

> After you've attempted the challenge, check your solution below:

Clicking 'solution' doesn't seem to be doing anything at times.

`... ```
`

Missing the beginning ```. Broken code, has 'Hello World' as the heading.

Markdown for code is inconsistent. Change to html?

**Comment by dionlarson** [comment]
Opting to fix the syntax highlights at the render engine level. Just submitted a PR to the eng team for this.
